# Numpy array indexing

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)

In [3]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [4]:
arr[8]

8

In [5]:
arr[0:]

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [6]:
arr[3:5]

array([3, 4])

In [7]:
arr[1:5]

array([1, 2, 3, 4])

In [8]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [10]:
arr = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [11]:
arr

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [13]:
arr[0][0]

5

In [14]:
arr[2][2]

45

In [15]:
arr[0,2]

15

In [16]:
arr[1,2]

30

In [17]:
arr[:2,1:]

array([[10, 15],
       [25, 30]])

In [19]:
arr= np.arange(1,11)

In [20]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [28]:
bool_arr = arr>5

In [27]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [29]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [31]:
array_2d = np.arange(50).reshape(5,10)

In [32]:
array_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [37]:
array_2d[1:3,5:7]

array([[15, 16],
       [25, 26]])