# Numpy ARrays

In [5]:
my_list =[1,2,3]

In [6]:
my_list

[1, 2, 3]

In [3]:
import numpy as np

In [8]:
arr = np.array(my_list)

In [9]:
arr

array([1, 2, 3])

# Two dimensional array

In [10]:
my_mat=[[1,2,3],[4,5,6],[7,8,9]]

In [11]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [18]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# CREATING ARRAY USING Numpy arange method

In [16]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

# CREATING ARRAY OF ZEROS

In [21]:
np.zeros(3)

array([0., 0., 0.])

In [ ]:
np.zeros((2,3))

# CREATING ARRAY OF ONES

In [26]:
np.ones(4)

array([1., 1., 1., 1.])

In [27]:
np.ones((2,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# LINSPACE
* IS USED TO CREATE A NUMBER OF EVENLY POINT YOU WANT*

In [28]:
np.linspace(0,100)

array([  0.        ,   2.04081633,   4.08163265,   6.12244898,
         8.16326531,  10.20408163,  12.24489796,  14.28571429,
        16.32653061,  18.36734694,  20.40816327,  22.44897959,
        24.48979592,  26.53061224,  28.57142857,  30.6122449 ,
        32.65306122,  34.69387755,  36.73469388,  38.7755102 ,
        40.81632653,  42.85714286,  44.89795918,  46.93877551,
        48.97959184,  51.02040816,  53.06122449,  55.10204082,
        57.14285714,  59.18367347,  61.2244898 ,  63.26530612,
        65.30612245,  67.34693878,  69.3877551 ,  71.42857143,
        73.46938776,  75.51020408,  77.55102041,  79.59183673,
        81.63265306,  83.67346939,  85.71428571,  87.75510204,
        89.79591837,  91.83673469,  93.87755102,  95.91836735,
        97.95918367, 100.        ])

# CREATING IDENTITY MATRIX USING numpy
*A dimentional matrix is a square matrix of the same rows and Columns with a diagonal of ones*

In [29]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

# CREATING A RANDOM NUMBER

In [31]:
np.random.rand(5)

array([0.7583465 , 0.47651494, 0.28843168, 0.36536089, 0.71845528])

In [32]:
np.random.rand(5,5)

array([[0.12440503, 0.56471805, 0.23643448, 0.62244955, 0.99704568],
       [0.81432023, 0.91870129, 0.31560242, 0.58424275, 0.20182675],
       [0.99989277, 0.73108392, 0.11712381, 0.63766229, 0.95232777],
       [0.01128791, 0.37808713, 0.46944722, 0.77351032, 0.12953266],
       [0.12382127, 0.01677377, 0.75518287, 0.78077321, 0.72090796]])

In [33]:
np.random.randn(2)

array([-1.18739852, -0.89733076])

In [34]:
np.random.randn(4,4)

array([[ 1.10509422, -0.58026934,  0.53386696, -0.26008285],
       [ 0.05883862, -1.1506138 ,  0.31732675, -1.2377472 ],
       [ 1.72209262, -0.83122112, -2.6345463 ,  0.56138826],
       [-1.94697976,  0.07442378,  3.42692621, -0.2054822 ]])

In [37]:
my_arr = np.random.randint(1,100,20)

In [38]:
my_arr 

array([48, 62, 19, 30, 99, 56, 20, 37, 18, 54, 14, 42, 69, 97, 34, 29, 67,
       75, 48, 40])

In [42]:
my_arr .reshape(4,5)

array([[48, 62, 19, 30, 99],
       [56, 20, 37, 18, 54],
       [14, 42, 69, 97, 34],
       [29, 67, 75, 48, 40]])